### ISSUE TITLE
第一次接触wordpress，改如何搭建呢。希望出个稍微详细的教程，谢谢

### ISSUE THREAD

**Issue by adzcsx2** [frankcuddy/OnlineGameCMS#1]
第一次接触wordpress，改如何搭建呢。希望出个稍微详细的教程，谢谢

**Comment by arkarkyaw88** [comment]
Any advice for existing wp site can be use this plugin and divided with game categories?

**Comment by frankcuddy** [comment]
> 

联系Q: 3394389416
